stages:
  - build
  - notify

build-frontend-code-job:
  stage: build
  script:
    - echo "BUILD_FRONTEND_JOB_ID=${CI_JOB_ID}" > frontend_job_variables.env
    - cd frontend
    - npm install
    - npm run build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes:
        - frontend/**/*
  artifacts:
    paths:
      - frontend/dist/frontend
      - frontend_job_variables.env

telegram-notification-frontend:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes:
        - frontend/**/*
  variables:
    API_TELEGRAM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  script:
    - source frontend_job_variables.env
    - |
      curl -X POST "${API_TELEGRAM}" -H "Content-Type: application/json" --data "{\"chat_id\":\"-1002185373712\", \"text\":\"Дмитрий Третьяков собрал frontend-приложение. URL артефакта ${CI_PROJECT_URL}/-/jobs/${BUILD_FRONTEND_JOB_ID}/artifacts/download\"}"
  needs:
    - build-frontend-code-job