cache:
  paths:
    - frontend/dist/frontend

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release

build-frontend-code-job:
  stage: build
  script:
    - echo "BUILD_FRONTEND_JOB_ID=${CI_JOB_ID}" > frontend_job_variables.env
    - cd frontend
    - npm install
    - npm run build
  rules:
    - changes: 
      - frontend/**/*

upload-frontend-release:
  stage: release
  only:
     changes:
     - frontend/**/* 
  needs:
    - build-frontend-code-job
  script:
    - cd frontend/dist
    - tar czvf sausage-store-${VERSION}.tar.gz frontend
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
      --upload-file sausage-store-${VERSION}.tar.gz
      ${NEXUS_REPO_URL}/${NEXUS_REPO_FRONTEND_NAME}/${VERSION}/sausage-store-${VERSION}.tar.gz