cache:
  paths:
    - frontend/dist/frontend

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - release

build-frontend-code-job:
  stage: build
  script:
    - echo "BUILD_FRONTEND_JOB_ID=${CI_JOB_ID}" > frontend_job_variables.env
    - cd frontend
    - npm install
    - npm run build
  only:
    - pushes
    - merge_requests
  artifacts:
    paths:
      - frontend/dist/frontend
      - frontend_job_variables.env

upload-frontend-release:
  stage: release
  only:
    - pushes
    - merge_requests
  needs:
    - build-frontend-code-job
  script:
    - cd frontend/dist
    - tar czvf sausage-store-${VERSION}.tar.gz frontend
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
      --upload-file sausage-store-${VERSION}.tar.gz
      ${NEXUS_REPO_URL}/${NEXUS_REPO_FRONTEND_NAME}/${VERSION}/sausage-store-${VERSION}.tar.gz