variables:
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  VERSION: 1.0.${CI_PIPELINE_ID}
  JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository # для хранения зависимостей бэкенда

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - release

build-backend-code-job:
  stage: build
  script:
    - echo "BUILD_BACKEND_JOB_ID=${CI_JOB_ID}" > backend_job_variables.env
    - cd backend
    - >
      mvn package
      -Dversion.application=${VERSION}
      -Dmaven.repo.local=${MAVEN_REPO_PATH}
  only:
    - pushes
    - merge_requests
  cache:
    policy: pull-push
    unprotect: false
    untracked: false
    when: on_success
    key: maven
    paths:
      - .m2/repository
  artifacts:
    expire_in: 1 day
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
      - backend_job_variables.env

upload-backend-release:
  stage: release
  only:
    - pushes
    - merge_requests
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - >
      mvn deploy -DskipTests
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
      -s settings.xml -Dversion.application=${VERSION} 
  
  