build-backend-code-job:
  stage: build
  script:
    - echo "BUILD_BACKEND_JOB_ID=${CI_JOB_ID}" > backend_job_variables.env
    - cd backend
    - mvn package
  only:
    changes:
      - backend/**/*
  cache:
    policy: pull-push
    unprotect: false
    untracked: false
    when: on_success
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    expire_in: 1 day
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
      - backend_job_variables.env

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  only:
    changes:
      - backend/**/*
  cache:
    policy: pull-push
    unprotect: false
    untracked: false
    when: on_success
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  allow_failure: true
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true 
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK} 
      -Dsonar.host.url=${SONAR_URL} 
      -Dsonar.login=${SONAR_LOGIN_BACK} 
      -Dsonar.projectName=${SONAR_PROJECT_NAME_BACK}
  needs:
    - build-backend-code-job

semgrep-sast:
  stage: test
  rules:
    - changes: 
      - backend/**/*
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: "$CI_PROJECT_DIR/.m2/repository"
  needs:
    - build-backend-code-job

telegram-notification-backend:
  stage: notify
  only:
    changes:
      - backend/**/*
  variables:
    API_TELEGRAM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  script:
    - source backend_job_variables.env
    - |
      curl -X POST "${API_TELEGRAM}" -H "Content-Type: application/json" --data "{\"chat_id\":\"-1002185373712\", \"text\":\"Дмитрий Третьяков собрал backend-приложение. URL артефакта ${CI_PROJECT_URL}/-/jobs/${BUILD_BACKEND_JOB_ID}/artifacts/download\"}"
  needs:
    - build-backend-code-job
    - sonarqube-backend-sast
    - semgrep-sast
  