variables:
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  VERSION: 1.0.${CI_PIPELINE_ID}
  JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository # для хранения зависимостей бэкенда

stages:
  - build
  - release

build-backend-code-job:
  stage: build

  script:
    - echo "BUILD_BACKEND_JOB_ID=${CI_JOB_ID}" > backend_job_variables.env
    - cd backend
    - >
      mvn package
      -Dversion.application=${VERSION}
      -Dmaven.repo.local=${MAVEN_REPO_PATH}
  rules:
    - changes: 
      - backend/**/*
  cache:
    policy: pull-push
    unprotect: false
    untracked: false
    when: on_success
    key: maven
    paths:
      - .m2/repository

upload-backend-release:
  stage: release
  only:
     changes:
     - backend/**/* 
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - >
      mvn deploy -DskipTests
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
      -s settings.xml -Dversion.application=${VERSION} 
  
  